name: "💻 Live Coding Suggestion"
description: Suggest a topic to cover in a live coding stream
labels: ["live-coding"]
body:
  - type: textarea
    id: description
    attributes:
      label: "What should I build or explore?"
      description: "Describe the live coding idea — app, library, challenge, or experiment."
    validations:
      required: true
  - type: textarea
    id: goals
    attributes:
      label: "What should viewers learn?"
      description: "Optional: specific takeaways, frameworks, techniques."
