name: "🎥 YouTube Video Suggestion"
description: Suggest a topic for a YouTube video
labels: ["video"]
body:
  - type: textarea
    id: description
    attributes:
      label: "Description"
      description: "What should this video explain/show/demo?"
    validations:
      required: true
  - type: input
    id: references
    attributes:
      label: "References / Links"
      placeholder: "Optional: related blog posts, docs, repos"
